# Generated by Django 5.0.5 on 2024-06-10 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comuna', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('numero_de_casa', models.IntegerField()),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateField()),
                ('cantidad_ventas', models.IntegerField()),
                ('transacciones', models.IntegerField()),
                ('cantidad_miembros', models.IntegerField()),
                ('ingresos_ventas', models.IntegerField()),
                ('gastos_ventas', models.IntegerField()),
                ('gastos_no_ventas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Y_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('fecha_de_ingreso', models.DateTimeField()),
                ('venta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('viña', models.CharField(max_length=150)),
                ('cepa', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cosecha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('nombre_prov', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email_empresa', models.EmailField(max_length=254, null=True)),
                ('telefono_empresa', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alerta', models.DateField()),
                ('id_inventario', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='website.inventario_y_stock')),
            ],
        ),
        migrations.AddField(
            model_name='inventario_y_stock',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.producto'),
        ),
        migrations.CreateModel(
            name='Compra_proveedores',
            fields=[
                ('OC', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_oc', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('numero_factura', models.IntegerField()),
                ('fecha_factura', models.DateField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(null=True)),
                ('costo_unitario', models.IntegerField(null=True)),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.producto')),
                ('nombre_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.IntegerField(unique=True)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('medio_de_pago', models.CharField(max_length=50)),
                ('SKU', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='website.producto')),
            ],
        ),
    ]
