# Generated by Django 5.0.5 on 2024-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comuna', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('numero_de_casa', models.IntegerField()),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
