# Generated by Django 5.0.5 on 2024-06-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_proveedores',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
