# Generated by Django 5.0.6 on 2024-07-17 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='valor',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
