# Generated by Django 5.0.6 on 2024-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_compra_proveedores_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='SKU',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='medio_de_pago',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='numero_boleta',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='ventas',
            name='comprador',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fecha_boleta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='flete',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='pago',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='pedido',
            field=models.CharField(default='0', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='venta_total',
            field=models.IntegerField(null=True),
        ),
    ]
