# Generated by Django 5.0.5 on 2024-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_cliente_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50)),
                ('fecha_y_hora', models.DateTimeField()),
                ('numero_boleta', models.IntegerField(unique=True)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('medio_de_pago', models.CharField(max_length=50)),
            ],
        ),
    ]
