# Generated by Django 5.0.5 on 2024-10-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_configuracion_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
