# Generated by Django 5.0.5 on 2024-07-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_ventas_sku_remove_ventas_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_y_stock',
            name='mov_bodegas',
            field=models.IntegerField(),
        ),
    ]
