# Generated by Django 5.0.6 on 2024-05-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_Y_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50, unique=True)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('fecha_de_ingreso', models.DateTimeField()),
                ('Venta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prov', models.CharField(max_length=50)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('email_empresa', models.EmailField(max_length=254)),
                ('numero_de_casa', models.IntegerField()),
                ('telefono_empresa', models.IntegerField()),
                ('producto_prov', models.CharField(max_length=50)),
                ('SKU_prov', models.CharField(max_length=50)),
            ],
        ),
    ]
