# Generated by Django 5.0.6 on 2024-05-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_inventario_y_stock_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra_proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_casa', models.IntegerField()),
                ('Calle_casa', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('SKU_prov', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='numero_de_casa',
        ),
    ]
