# Generated by Django 5.0.5 on 2024-05-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_compra_proveedores_remove_proveedores_numero_de_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateField()),
                ('cantidad_ventas', models.IntegerField()),
                ('transacciones', models.IntegerField()),
                ('cantidad_miembros', models.IntegerField()),
                ('ingresos_ventas', models.IntegerField()),
                ('gastos_ventas', models.IntegerField()),
                ('gastos_no_ventas', models.IntegerField()),
            ],
        ),
    ]
