# Generated by Django 5.0.5 on 2024-05-26 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_informes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('fecha_fabricacion', models.DateField()),
                ('tipo_producto', models.CharField(max_length=50)),
                ('viña', models.CharField(max_length=150)),
                ('cepa', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cosecha', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='fecha_y_hora',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.producto'),
        ),
    ]
