# Generated by Django 5.0.5 on 2024-05-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_producto_remove_ventas_fecha_y_hora_alter_ventas_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta_informes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.IntegerField()),
                ('fecha_alerta', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Alerta_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50)),
                ('fecha_alerta', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='compra_proveedores',
            old_name='SKU_prov',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='inventario_y_stock',
            old_name='SKU',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='SKU_prov',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='SKU',
            new_name='sku',
        ),
    ]
