# Generated by Django 5.0.5 on 2024-05-31 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alerta_informes_alerta_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_fabricacion',
        ),
    ]
