# Generated by Django 5.0.5 on 2024-06-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_sku_alerta_stock_sku_rename_sku_producto_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='sku',
            new_name='SKU',
        ),
    ]
