# Generated by Django 5.0.5 on 2024-06-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_sku_producto_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta_stock',
            old_name='sku',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='compra_proveedores',
            old_name='sku',
            new_name='SKU_prov',
        ),
        migrations.RenameField(
            model_name='inventario_y_stock',
            old_name='sku',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='sku',
            new_name='SKU_prov',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='sku',
            new_name='SKU',
        ),
    ]
