# Generated by Django 5.0.5 on 2024-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_sku_alerta_stock_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='SKU_prov',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='producto_prov',
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='rut_empresa',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
