# Generated by Django 5.0.6 on 2024-06-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_proveedores_sku_prov_remove_proveedores_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario_y_stock',
            old_name='Venta',
            new_name='venta',
        ),
    ]
