# Generated by Django 5.0.6 on 2024-06-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_venta_inventario_y_stock_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_y_stock',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.producto'),
        ),
        migrations.AlterField(
            model_name='inventario_y_stock',
            name='venta',
            field=models.CharField(max_length=50),
        ),
    ]
