# Generated by Django 5.0.6 on 2024-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_inventario_y_stock_sku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario_y_stock',
            old_name='venta',
            new_name='cepa',
        ),
        migrations.AddField(
            model_name='inventario_y_stock',
            name='bodega',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario_y_stock',
            name='cosecha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario_y_stock',
            name='mov_bodegas',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario_y_stock',
            name='precio_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario_y_stock',
            name='salidas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario_y_stock',
            name='stock',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario_y_stock',
            name='viña',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
