# Generated by Django 5.0.6 on 2024-06-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_venta_inventario_y_stock_cepa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_y_stock',
            name='nombre_prov',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
