# Generated by Django 5.0.6 on 2024-06-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_nombre_prov_inventario_y_stock_nombre_provv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario_y_stock',
            old_name='nombre_provv',
            new_name='nombre_prov',
        ),
    ]
