# Generated by Django 5.0.6 on 2024-06-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_nombre_provv_inventario_y_stock_nombre_prov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario_y_stock',
            name='nombre_prov',
        ),
    ]
