# Generated by Django 5.0.6 on 2024-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_inventario_y_stock_nombre_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_y_stock',
            name='nombre_prov',
            field=models.CharField(default=5, max_length=150),
            preserve_default=False,
        ),
    ]
